### ISSUE TITLE
Background color is improperly applied to separated graphics

### ISSUE THREAD

**Issue by isocosa** [peterkvt80/wxted#10]
The background color seems to get incorrectly applied to separated graphics.
The gaps between the pixels of the separated graphics seem to inherit the background color of the character above (unless the character above is separated graphics, then it uses black) it instead of using the actual background color.

Here's a screenshot
![wxted_bug](https://user-images.githubusercontent.com/38756203/54088309-08ca3580-435d-11e9-86ea-5ba2f45f3e45.png)

And a .zip file with a .tti file showcasing the bug
[bgbug.zip](https://github.com/peterkvt80/wxted/files/2949743/bgbug.zip)

**Comment by peterkvt80** [comment]
Thanks for that clear report. I have rewritten the graphics drawing section to render this correctly in version 1.36.
