### ISSUE TITLE
ALT key shows hidden codes

### ISSUE THREAD

**Issue by wimpie3** [peterkvt80/wxted#14]
The ALR-GR key shows the hidden codes. Works perfect.

However, I've noticed that pressing ALT twice shows the hidden codes as well. When ALT-TABbing to another window and returning to wxted, this sometimes causes the hidden codes to show.

**Comment by peterkvt80** [comment]
Both ALT keys were enabled to toggle the hidden characters. Unfortunately this made it a little tricky to use the ALT key. The ALT key will be ignored in V1,45.
