### ISSUE TITLE
Go to first character of new line at the end

### ISSUE THREAD

**Issue by wimpie3** [peterkvt80/wxted#15]
Could you please position the cursor on the first character of the next row when you've reached the end of a line with the cursor? You now have to manually return the cursor to the next line when typing in a long text.

**Comment by peterkvt80** [comment]
Primitive text wrap added. It avoids overwriting up to three control codes by skipping over them. A more useful addition would be a wrap that takes into account word gaps but that is much more complicated so maybe later. Available from release 1.45.
