### ISSUE TITLE
Double height graphics not implemented

### ISSUE THREAD

**Issue by wimpie3** [peterkvt80/wxted#18]
Double height graphics do not seem to be implemented?

**Comment by peterkvt80** [comment]
It is implemented but I think it is quite buggy. I didn't fix it up until now because it is probably the least useful feature of teletext.

**Comment by premultiply** [comment]
> it is probably the least useful feature of teletext.

Don't say that! ;-)

**Comment by peterkvt80** [comment]
Looks like I got half way through implementing it then lost interest.  I have now finished it in v1.45
