### ISSUE TITLE
Issues saving file on Windows 10

### ISSUE THREAD

**Issue by helgrind** [peterkvt80/wxted#2]
If I save as a tti file on my Windows 10 laptop, wxTED and 'recent files' can find the file, but not the main explorer window or notepad to edit etc. Worked fine on Wine. So far I'm exporting to edit.tf then saving to tti.

**Comment by peterkvt80** [comment]
There are a few things that could be implemented to integrate better with Windows. It doesn't have any of the convenience methods like adding to the recent file list, It doesn't do file associations or preview thumbnails. I'll add this to me to-do list.

**Comment by helgrind** [comment]
Something I noticed at work the other day, which I haven't had time to check, is that the new explorer windows have a 'Compatibility Files' button on the ribbon at the top which can be used to solve problems with files exhibiting similar behaviour (i.e. seeing them in dialogue boxes but not in the main explorer app). I'll check this out.

**Comment by peterkvt80** [comment]
The latest packaged version adds file associations. You can click on a tti file to launch wxTED. tti files should also get a Teddy icon. Page opening history should also get picked up by recent files.
