### ISSUE TITLE
No difference between save of TTI or TTIX files

### ISSUE THREAD

**Issue by wimpie3** [peterkvt80/wxted#20]
No matter if you save a file as TTI or TTIX, both times the file is ASCII only (<127). I'd expect one of the two files to contain characters > 127.

**Comment by peterkvt80** [comment]
TTI can be 7 or 8 bit. I added TTIX as a 7 bit format because 8 bit is sometimes difficult to handle. In the next version I think I'll make TTI 8 bit and TTIX 7 bit as long as it doesn't mess up any of the viewers likely to use it.

**Comment by ZXGuesser** [comment]
I took 8-bit TTI export out of all my code because it causes so many issues, and rather hoped it would just be forgotten about. They should still import ok though.

**Comment by peterkvt80** [comment]
I'm remembering the horror now. How Ascii codes >127 and UTF8 don't play well together especially in Javascript. How double height gets mangled. I suggest if you really want 8 bit files you run it through a 7 bit to 8 bit converter which should be a dozen lines of python.

**Comment by nat2001** [comment]
I really don't know why you'd want 8-bit files anyway. Last time I checked
vbit2 didn't even support them

**Comment by ZXGuesser** [comment]
Hmm, it should do but it's entirely possible I've broken it and not noticed since getting rid of 8-bit tti files everywhere else!

**Comment by peterkvt80** [comment]
ttix files and tti files are both read by the same code so it doesn't matter which one is 7 or 8 bit. However, the output is only 7 bit as that is more compatible and generally easier to handle.
