### ISSUE TITLE
How to Publish Page to TEEFAX/CEEFAX?

### ISSUE THREAD

**Issue by MICR-OSOFT** [peterkvt80/wxted#22]
I'm very confused. I couldn't find no document covering this. Any help is welcome

**Comment by avrovulcanxh607** [comment]
Teefax and Ceefax are made available as Subversion (SVN) repositories - as such, to publish pages to them you must ask their respective owners for a contributer's account, download SVN and commit your pages to the service.

**Comment by peterkvt80** [comment]
Publishing pages is not handled by Vbit2 but by external repository servers. Teefax uses svn and is explained here https://docs.google.com/document/d/1rZ7Z_ZYhK8fHTocaQC0c7g97hT1vkdhTahpgJ0wiSgg/edit?usp=sharing.

**Comment by peterkvt80** [comment]
To avoid confusion, I will remove the Publish functions. They were based on FTP and are not suitable for modern security standards.
