### ISSUE TITLE
T42.h not found, building for raspberry pi

### ISSUE THREAD

**Issue by veryalien** [peterkvt80/wxted#24]
When I try to build wxted from the latest cloned source in code::blocks on a raspberry pi, I get an error that T42.h can't be included.
I can't find T42.h in the repository anywhere. What am I missing?
I suspect that not all of the required files have been committed in the last release?

Compiling and installing wxwidgets on the raspberry pi 4 went very well (once I'd manually installed gtk myself). It took a long time, but was successful.
One tiny error in your full instructions for wxted on the raspberry pi was that you need to run ../configure and not ./configure
You already cd to gtk_build so you need a double dot to get to the right directory for configure.

**Comment by peterkvt80** [comment]
Oops. I've now pushed the T42.h file. Thanks for the report.

**Comment by veryalien** [comment]
Thanks for the push. I started again with a new clone of the updated wxTED repository.
Now it includes T42.h and HeaderPacket.h but fails in the build on line 127 of ttxpage.cpp with:
undefined reference to 'HeaderPacket::HeaderPacket(T42&)'
I commented out the entire else from ttxpage.cpp lines 127 to 139, avoiding header_packet completely, it then builds successfully.
Running that version shows a wxTED welcome screen and I can open and edit pages from the wxTED Pages directory.
When I try to save any edits to a page it doesn't seem to save anything, but keeps running.
When I try to save as, it crashes with a segmentation fault.
To be honest, rather than all this, I think I'll use a different teletext page editor. The one from ZXGuesser at zxnet.co.uk seems to work in the raspberry pi chromium browser and exporting works. I think it's basically the same editor in a different form?

**Comment by peterkvt80** [comment]
The editors are made very differently. wxTED handles carousels but only using basic pages. ZXNet doesn't do carousels but handles some level 2.5. I think there is another bug that means on Linux that Save doesn't always work and you need to "Save As". I'll fire up the Raspberry Pi and look at fixing these problems.

**Comment by peterkvt80** [comment]
Restored page save. It was inadvertently deleted. Also updated project files for Codeblocks so that fixes the T42 missing references.
