### ISSUE TITLE
Save File Dialog

### ISSUE THREAD

**Issue by pjfdirect** [peterkvt80/wxted#4]
xwTED 1.27
Windows 7 Ultimate

During and after editing, I type ctrl-S or select File > Save to save my work. When I click wxTED's close box, select File > Quit or type alt-F4, the app tells me the file has not been saved and asks for confirmation of closure, despite there being no unsaved work.

On rare occasions it does not ask, but I haven't been able to re-create those circumstances.

**Comment by peterkvt80** [comment]
Version 1.30 tidies up the Page Changed detection to make it more reliable.
