### ISSUE TITLE
Row 0 and PgUp

### ISSUE THREAD

**Issue by pjfdirect** [peterkvt80/wxted#5]
I've ben updating Teefax TTIs where row 0 reads 'TEDFAX' so that it reads 'TEEFAX', to appear in the Teefax web viewer or when the file is opened in editors. If the cursor is in row 0 when I PgUp to another page in the current carousel, wxTED will sometimes crash with the error illustrated below. This sometimes leads to file damage, with later pages in the TTI lost. (I've been practising safe dev so the repo never suffers from these errors).

![image](https://cloud.githubusercontent.com/assets/23056210/24419748/2739da76-13e8-11e7-84bf-6ca84469a5dc.png)

**Comment by peterkvt80** [comment]
I fixed this at the end of March 2017. Sorry I forgot to close the issue.

**Comment by pjfdirect** [comment]
I just thought I'd somehow adopted content management habits that didn't trigger it :-) Thanks!
