### ISSUE TITLE
Opening file 

### ISSUE THREAD

**Issue by nat2001** [peterkvt80/wxted#7]
Opening a teletext page while another is already loaded usually results in a blank screen with the file name in it. It SOMETIMES will open the second file, but I have been unable to track down the circumstances or repeat this.

**Comment by peterkvt80** [comment]
There is a problem that I have seen with badly formed page files. It is something to do with subpages if they have no lines.

**Comment by nat2001** [comment]
The thing is that these aren't carousel pages, they are ordinary pages. I've tried this with both code generated and wxTED generated files, with the same result.

**Comment by nat2001** [comment]
I think it turns out that it was something to do with my computer - whether it is because it runs Windows XP or what, I don't know, but I re-installed the OS recently and it seems to be working much better now for whatever reason.
