### ISSUE TITLE
Version 1.30 for Windows fails to recognise Ctrl+I as "Steady" inserts code for a box start instead.

### ISSUE THREAD

**Issue by afarlie** [peterkvt80/wxted#8]
According to the documentation Ctrl+H begins flashing text and CTRL+I ends it.

In the noted version Ctrl+I generates the same control sequence as Ctrl+J, meaning it's not currently possible to cancel flash form the UI.

Has a switch statment been miscoded?

**Comment by isocosa** [comment]
In the latest version as of writing this (1.36) it places the right control character, however, it looks like "Steady" uses the same icon as "End Box" when control code display is enabled, which is indeed confusing.

**Comment by peterkvt80** [comment]
Thanks for that report. There was a missing break in the switch. The update is now pushed to the repo and will be fixed in the next release.
